export default function Center () {
  return (
    <div className='center__wrap'>
      <div className='center__container'>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
        <div>Center</div>
      </div>
    </div>
  )
}